In [8]:
import pandas as pd

In [9]:
nba_shots_Chicago_="shot log CHI.csv"

In [10]:
Chicago_shots=pd.read_csv(nba_shots_Chicago_)
Chicago_shots

,self previous shot,player position,home game,location x,opponent previous shot,home team,shot type,points,away team,location y,time,date,shoot player,time from last shot,quarter,current shot outcome
0,NaN,SG,Yes,239.0,NaN,CHI,Jump Shot,2,BOS,169.0,0:17,2016-10-27,Dwyane Wade,NaN,1,SCORED
1,SCORED,PF,Yes,64.0,MISSED,CHI,Hook Shot,2,BOS,215.0,1:08,2016-10-27,Taj Gibson,51.0,1,MISSED
2,MISSED,PG,Yes,67.0,MISSED,CHI,Driving Layup,2,BOS,259.0,1:15,2016-10-27,Rajon Rondo,7.0,1,MISSED
3,MISSED,C,Yes,102.0,MISSED,CHI,Hook Shot,2,BOS,243.0,1:27,2016-10-27,Robin Lopez,12.0,1,MISSED
4,MISSED,SG,Yes,241.0,SCORED,CHI,Jump Shot,2,BOS,210.0,1:57,2016-10-27,Dwyane Wade,30.0,1,MISSED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7134,SCORED,G,Yes,640.0,MISSED,CHI,Jump Shot,3,BRO,212.0,9:42,2017-04-12,Denzel Valentine,27.0,4,SCORED
7135,SCORED,G,Yes,675.0,MISSED,CHI,Jump Shot,3,BRO,113.0,10:13,2017-04-12,Denzel Valentine,31.0,4,MISSED
7136,MISSED,SG,Yes,848.0,SCORED,CHI,Jump Shot,2,BRO,112.0,10:39,2017-04-12,Anthony Morrow,26.0,4,SCORED
7137,SCORED,PF,Yes,691.0,MISSED,CHI,Jump Shot,3,BRO,99.0,11:10,2017-04-12,Bobby Portis,31.0,4,SCORED
7138,SCORED,G,Yes,661.0,MISSED,CHI,Jump Shot,3,BRO,372.0,11:32,2017-04-12,Denzel Valentine,22.0,4,MISSED